import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { useEffect, useState } from 'react';
import { CalendarPlus, CheckCircle2, Loader2, Save, Copy } from 'lucide-react';
import toast from 'react-hot-toast';
import { useQR } from '../../contexts/QRContext';
import { qrAPI } from '../../services/api';
import FormWrapper from '../../components/FormWrapper';

const schema = z.object({
  eventTitle: z.string().min(1, 'Event title is required'),
  location: z.string().optional(),
  startDate: z.string().min(1, 'Start date is required'),
  endDate: z.string().optional(),
  description: z.string().optional(),
  title: z.string().optional(),
});

const EventForm = () => {
  const { updateQRData, setActiveType, qrData, qrStyle, logo } = useQR();
  const [saving, setSaving] = useState(false);
  const [createdEventUrl, setCreatedEventUrl] = useState('');

  const { register, watch, handleSubmit, formState: { errors, isValid } } = useForm({
    resolver: zodResolver(schema),
    mode: 'onChange',
    defaultValues: {
      eventTitle: '',
      location: '',
      startDate: '',
      endDate: '',
      description: '',
    },
  });
  const values = watch();

  useEffect(() => {
    setActiveType('EVENT');
  }, [setActiveType]);

  // Event QR codes intentionally encode an HTTPS landing page instead of raw ICS.
  // Before saving, show a safe preview target. After saving, replace it with the
  // real event URL returned by the server.
  useEffect(() => {
    if (!createdEventUrl) {
      const serverUrl = import.meta.env.VITE_SERVER_URL || 'http://localhost:5000';
      updateQRData(`${serverUrl.replace(/\/$/, '')}/event/preview`);
    }
  }, [createdEventUrl, updateQRData]);

  const handleCreate = async () => {
    if (!isValid) return;
    setSaving(true);
    try {
      const response = await qrAPI.create({
        title: values.eventTitle || 'Event QR Code',
        type: 'EVENT',
        dynamic: true,
        destination: '',
        payload: values,
        style: qrStyle,
        logo,
      });

      const eventUrl = response.data?.publicUrl || response.data?.destination;
      if (!eventUrl) throw new Error('Event URL was not generated by the server.');

      setCreatedEventUrl(eventUrl);
      updateQRData(eventUrl);
      toast.success('Event QR created — Samsung/iPhone compatible event page is ready.');
    } catch (err) {
      toast.error(err.message || 'Could not create Event QR');
    } finally {
      setSaving(false);
    }
  };

  const handleCopy = async () => {
    if (!createdEventUrl) return;
    await navigator.clipboard.writeText(createdEventUrl);
    toast.success('Event URL copied');
  };

  return (
    <FormWrapper
      title="Event QR Code"
      icon="📅"
      description="Scan opens a mobile event page with reliable calendar options on Samsung, Android and iPhone."
      type="EVENT"
      formData={values}
      dynamic={false}
    >
      <div className="p-3.5 rounded-xl bg-brand-500/10 border border-brand-500/20 space-y-2">
        <div className="flex items-center gap-2 text-xs font-bold text-brand-300">
          <CalendarPlus size={14} />
          Universal Event QR
        </div>
        <p className="text-[11px] leading-5 text-slate-400">
          The QR contains a short HTTPS event link. Samsung and iPhone scanners open the event page first, where the user can add the event to their calendar or download an .ics file.
        </p>
      </div>

      <div>
        <label className="label">Event Title *</label>
        <input {...register('eventTitle')} className="input" placeholder="Product Launch Party" />
        {errors.eventTitle && <p className="field-error">{errors.eventTitle.message}</p>}
      </div>

      <div className="grid grid-cols-2 gap-3">
        <div>
          <label className="label">Start Date & Time *</label>
          <input type="datetime-local" {...register('startDate')} className="input" />
          {errors.startDate && <p className="field-error">{errors.startDate.message}</p>}
        </div>
        <div>
          <label className="label">End Date & Time</label>
          <input type="datetime-local" {...register('endDate')} className="input" />
        </div>
      </div>

      <div>
        <label className="label">Location</label>
        <input {...register('location')} className="input" placeholder="Conference Hall, Lahore" />
      </div>

      <div>
        <label className="label">Description</label>
        <textarea {...register('description')} className="input min-h-[80px] resize-y" placeholder="Event details..." />
      </div>

      <div className="pt-2 border-t border-surface-800 space-y-2">
        <button
          type="button"
          onClick={handleCreate}
          disabled={!isValid || saving}
          className="btn-primary w-full py-2.5 text-xs font-bold flex items-center justify-center gap-2 disabled:opacity-50 disabled:cursor-not-allowed"
        >
          {saving ? <Loader2 size={14} className="animate-spin" /> : createdEventUrl ? <CheckCircle2 size={14} /> : <Save size={14} />}
          {saving ? 'Creating Event QR...' : createdEventUrl ? 'Event QR Saved ✓' : 'Create & Save Event QR'}
        </button>

        {createdEventUrl && (
          <div className="space-y-2">
            <div className="flex items-center gap-2">
              <input readOnly value={createdEventUrl} className="input bg-surface-900 font-mono text-[11px] text-brand-300" />
              <button type="button" onClick={handleCopy} className="btn-secondary px-3 py-2 text-xs flex items-center gap-1.5">
                <Copy size={13} /> Copy
              </button>
            </div>
            <p className="text-[10px] text-emerald-400 flex items-center gap-1">
              <CheckCircle2 size={11} /> This URL is what your QR code now encodes.
            </p>
          </div>
        )}
      </div>
    </FormWrapper>
  );
};

export default EventForm;
